### ISSUE TITLE
Issues noted by Vizlab team walk-through

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/ds-pipelines-targets-2-course#14]
Put your issues here!

**Comment by jordansread** [comment]
- Should recommend installing `visNetwork` before using `targets::tar_glimpse()` (e.g., [here](https://github.com/jread-usgs/ds-pipelines-targets-2/issues/3#issuecomment-867542540))
- for "The output of tar_visnetwork() after running tar_make('site_data_styled') (and having never run tar_make())" I thought this was a little confusing. "having never run tar_make()" would mean the site_data target is not up to date, but it is shown as complete. From [here](https://github.com/USGS-R/ds-pipelines-targets-2-course/blob/9344a95fa021c60bca2fafb469be391b2083c6ea/responses/13-target-status.md)

**Comment by hcorson-dosch-usgs** [comment]
In issue 3 of the course, comment 7:
> Note that you'd also need to modify your combine_into_df function to use dir(work_dir) to generate the file names since in_dir is just the name of the directory.

`dir(work_dir)` should be `dir(in_dir)`

**Comment by hcorson-dosch-usgs** [comment]
In issue 10 of the course, the comment ends with:
> Once your pull request has been merged return here and comment on this issue

But the next comment (it starts with "You are nearly done with the second pipelines course! We have a few final thoughts before you level up your pipelines capability 🏆") actually shows up in your PR instead, after it is merged.

It still ends with "Close this issue to continue" even though it's in a merged PR

So you have to go back to issue 10 and close it to see the prompt to go to the next issue


** edited to add:

Realized I may have inadvertently triggered that by commenting in the PR before merging it? Not sure exactly how the bot is programmed.

**Comment by lindsayplatt** [comment]
> * Should recommend installing `visNetwork` before using `targets::tar_glimpse()` (e.g., [here](https://github.com/jread-usgs/ds-pipelines-targets-2/issues/3#issuecomment-867542540))
> * for "The output of tar_visnetwork() after running tar_make('site_data_styled') (and having never run tar_make())" I thought this was a little confusing. "having never run tar_make()" would mean the site_data target is not up to date, but it is shown as complete. From [here](https://github.com/USGS-R/ds-pipelines-targets-2-course/blob/9344a95fa021c60bca2fafb469be391b2083c6ea/responses/13-target-status.md)

Replying to @jread-usgs: 

* Great catch! I guess I already had that package from somewhere else. It looks like `targets` only _suggests_ it, so I will include it in the list of packages to install.
* I see how that is confusing. The sentence is trying to say here is what the status is after it only builds the specific target `site_data_styled`, but has not built **_all_** the targets (by running `tar_make()` without any args). I will edit to make that less confusing.
