### ISSUE TITLE
Changes to site `01435000` that are causing pipeline failures.

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/ds-pipelines-targets-2-course#17]
[Site 01435000](https://waterdata.usgs.gov/nwis/uv?01435000) now has multiple temperature columns, so doesn't return the same column names as the other sites in this repo. This causes a failure in the `process_data` function. I suggest we drop this site altogether, and either have one fewer site or pick a less complicated site.

**Comment by lindsayplatt** [comment]
Oh bummer! Thanks for catching this with Ellie. Will change before the next cohort takes this!

**Comment by lindsayplatt** [comment]
Dropping the site. Unfortunately, it was used as one of the two sites in some early examples, so making edits using one of the other sites.

For `12-visualize-pipeline.md`:
![image](https://user-images.githubusercontent.com/13220910/133107103-47735575-9f40-427e-b66c-32ba32102d91.png)

For `13-target-status.md`:
![image](https://user-images.githubusercontent.com/13220910/133108278-d1095b74-b810-49a2-bdfb-310598e07c8b.png)

**Comment by shamshaw** [comment]
Site 0143500 is still showing up in the training for the new cohort and resulting in errors appearing while building the pipeline in the targets-2 training. Does the updated code dropping this site need to get pushed out to a template still?

**Comment by lindsayplatt** [comment]
🤦 🤦 🤦 🤦 🤦 🤦 🤦 

well, this **_STILL_** [open PR](https://github.com/USGS-R/ds-pipelines-targets-2-template/pull/2) explains why those changes were not brought in :( Guess I missed the last, critical step of clicking the big green button.

**Comment by jpadilla-usgs** [comment]
The figures Lindsay linked above were not updated in the training. I will close this issue once I resolve a PR that updates the figures Lindsay create above.
