### ISSUE TITLE
debugging in targets

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/ds-pipelines-targets-2-course#3]
On my Mac, I see this ugliness when I add a `browser()` line and run `tar_make(callr_function=NULL)`.

![image](https://user-images.githubusercontent.com/12039957/116103724-de8f7b00-a67d-11eb-97cd-7950a438c8ad.png)

It does work, though. The next line is `Browse[1]>`, which I can then use to inspect the environment and step through the code.

![image](https://user-images.githubusercontent.com/12039957/116103946-0da5ec80-a67e-11eb-89a0-0e5018973663.png)

Here's the whole session, in case you want to use the image in the course.

![image](https://user-images.githubusercontent.com/12039957/116103677-d1728c00-a67d-11eb-80e2-55624c368bcb.png)

**Comment by aappling-usgs** [comment]
I would have hoped for these browser buttons in my console pane:

![image](https://camo.githubusercontent.com/bf6eba5f6919e2002189462bb746b9d27b90d306261ddc378a61faba5c30efba/68747470733a2f2f737570706f72742e7273747564696f2e636f6d2f68632f656e2d75732f61727469636c655f6174746163686d656e74732f3230313539343734372f636f6e736f6c652d746f6f6c6261722e706e67)

But they're not there.

![image](https://user-images.githubusercontent.com/12039957/116104457-742b0a80-a67e-11eb-8961-e85aca65d073.png)

So instead of those buttons, I have to type `n` for 'run the next statement', `s` for 'step into the function', `c` for 'continue running', `f` to 'finish the function or loop', and `Q` for 'exit the debugger'. As noted in [the RStudio docs](https://support.rstudio.com/hc/en-us/articles/205612627-Debugging-with-RStudio#debugging-commands), "All of these commands are documented in the R help page for browser(); you can also type `help` at the `Browse[N]>` prompt to see them."

The printout of `Browse[N]> help` is pretty good - concise and useful:
![image](https://user-images.githubusercontent.com/12039957/116105885-bdc82500-a67f-11eb-86fc-ee3a641a82a5.png)

**Comment by aappling-usgs** [comment]
Ohh, but I finally got around to trying to debug my debugger, googled the error message, learned that it [may have been fixed](https://community.rstudio.com/t/rstudio-crashes-when-debugging/47214/4) in v1.3.5036-1, and realized my RStudio is way out of date:

![image](https://user-images.githubusercontent.com/12039957/116106478-21eae900-a680-11eb-9e4a-5b0deaec8cd2.png)

and oh, hey, that does it! Now I get the complete, and much better, RStudio debugging experience. But I still like using the shortcut commands (n, s, f, c, Q, where, help) rather than the buttons (personal preference for keeping hands on the keyboard).

![image](https://user-images.githubusercontent.com/12039957/116110613-dd614c80-a683-11eb-8269-5a6bf46fb0e5.png)

**Comment by lindsayplatt** [comment]
Glad it was a version update issue because I see 

![image](https://user-images.githubusercontent.com/13220910/116619503-23c5de00-a906-11eb-8348-3b46aa413a68.png)

when I run that command. 

For the course, I think I will just mention people should consider updating RStudio if they have <1.3.5 in order for the debugger experience to be as smooth as possible.

**Comment by lindsayplatt** [comment]
I think we solved this - it was an issue with a version of RStudio and has been captured in the course here https://github.com/USGS-R/ds-pipelines-targets-2-course/commit/4542d9a705a7434a3aa90df2b28533efc6b63a3f
