### ISSUE TITLE
Link to real DS example pipeline

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/ds-pipelines-targets-2-course#4]
At this time, **targets** is so new to DS that many of our pipelines are still in flux and may use some but not all of our best practices (which have changed as we've learned more). For this reason, we should revisit adding an example pipeline (see https://github.com/USGS-R/ds-pipelines-targets-2-course/pull/2#discussion_r627435357) later when our real examples are a bit more stable.

**Comment by lindsayplatt** [comment]
The current examples are only accessible on VPN. Should we change that?

**Comment by aappling-usgs** [comment]
I don't think that's true - our current real-world uses of targets are on code.usgs.gov, which I think means they can be made public and/or shared with arbitrary users in or beyond USGS. They ([res-temperature-process-models](https://code.usgs.gov/wma/wp/res-temperature-process-models), at least) are currently internal, though, and the switch to public seems to be beyond my control. So at least for now, you don't need VPN but do need a login with access.

![image](https://user-images.githubusercontent.com/12039957/117366843-597f3f80-ae8f-11eb-9722-fb2fed3f60dc.png)

**Comment by lindsayplatt** [comment]
Ahhh OK. I guess I misunderstood the exact method access but new they were not just visible. 👍

**Comment by aappling-usgs** [comment]
That much is certainly true.

**Comment by jpadilla-usgs** [comment]
https://github.com/DOI-USGS/ds-pipelines-targets-2-course/commit/ba337ed3fc2a112fe0bc96482c70e5edbc8a6d04
