### ISSUE TITLE
Verify that you don't need to close the last issue for the course to be "completed"

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/ds-pipelines-targets-2-course#6]
See https://github.com/USGS-R/ds-pipelines-targets-2-course/pull/2/files#r625986330

**Comment by lindsayplatt** [comment]
@jzwart is your course marked as complete here? https://lab.github.com/USGS-R/usgs-targets-tips-and-tricks/

**Comment by jzwart** [comment]
Yes. 
![image](https://user-images.githubusercontent.com/4825431/118186628-f1d77000-b40b-11eb-830a-69b3e81947ea.png)
And I still have last issue open https://github.com/jzwart/ds-pipelines-targets-2/issues/12

**Comment by lindsayplatt** [comment]
Yay! 🎉 This is what we want, so that you can return to that issue as a reference more easily.
