### ISSUE TITLE
function still has scmake() in the error message 

### ISSUE THREAD

**Issue by jzwart** [USGS-R/ds-pipelines-targets-2-course#7]
The `download_nwis_site_data` function has an error message that references `scmake()` rather than `tar_make()` 
```
  # -- simulating a failure-prone web-sevice here, do not edit --
  if (sample(c(T,F,F,F), 1)){
    stop(site_num, ' has failed due to connection timeout. Try scmake() again')
  }
```
This should be in `1_fetch/src/get_nwis_data.R`

**Comment by lindsayplatt** [comment]
Fixed by https://github.com/USGS-R/ds-pipelines-targets-2-template/pull/1
