### ISSUE TITLE
Add python example to targets 

### ISSUE THREAD

**Issue by jzwart** [USGS-R/ds-pipelines-targets-2-course#9]
It would be good to show how to run Python functions from R targets pipeline. Could use something like: 
```
np <- reticulate::import('numpy')
p1_targets_list = list(
  ...
  tar_target(obs_data_file, format='file'),
  tar_target(
    obs_data,
    np$load(obs_data_file)
  )
)
``` 
or add in a custom Python function.

**Comment by lindsayplatt** [comment]
Hmmm I think this should go near the end. I could see this going under [the "DS conventions" part](https://github.com/USGS-R/ds-pipelines-targets-2-course/blob/main/responses/40-datasci-conventions.md) by saying that these pipelines are _conventionally_ written in R, but sometimes Python functions/steps are needed. I could also see this being added to [the "final tips" part](https://github.com/USGS-R/ds-pipelines-targets-2-course/blob/main/responses/41-final-tips.md) to say that it is possible to incorporate Python into your pipeline.

**Comment by jzwart** [comment]
I think it might be best to put in the `final tips` portion? It seems like it might be too much to stick in with the DS conventions part. I don't think it's necessary that _everyone_ incorporate a python function into their targets pipeline for this course - so maybe just an 'extra tip' if you want to try.

**Comment by lindsayplatt** [comment]
Agreed! Is this something you would like to add to `final tips` in a PR?

**Comment by jzwart** [comment]
Yup I'll add and make a new PR
